In [21]:
%pip install kaggle 
import kaggle

Requirement already satisfied: kaggle in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.7.4.5)
Requirement already satisfied: bleach in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (2025.8.3)
Requirement already satisfied: charset-normalizer in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (6.32.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/ikawahyuni/Library/Python/3.13/lib/python/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (80.9.0)
Requirement already satisfied: six>=1.10 in /Users/ikawahyuni/Library/Python/3.13/lib/python/site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kaggle) (0.5.1)
Note: you may need to restart the kernel to use updated packages.

In [22]:
#check what is the format of the file in ZIP or already CSV
file_path = '/Users/ikawahyuni/Downloads/Project Portofolio/project 7 NETFLIX/netflix_titles.csv'
with open(file_path, 'rb') as f:
    head = f.read(200)
print(head[:200])


# the file is in csv format 
# #ID,Date,... → actual CSV

b'show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description\ns1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 m'

In [23]:
import pandas as pd 
file_path = '/Users/ikawahyuni/Downloads/Project Portofolio/project 7 NETFLIX/netflix_titles.csv'
df = pd.read_csv(file_path)
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [24]:
#the data is clean, we can load the data into sql server 
#if we use pip install pyodbc and that's not gonna work, 
# we use environment in Python 3 so we can use the code below
!python3 -m pip install pyodbc

Requirement already satisfied: pyodbc in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (5.3.0)

In [25]:
!python3 -m pip install --upgrade pip

Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (25.3)

In [26]:
pip install sqlalchemy psycopg2-binary pandas

Requirement already satisfied: sqlalchemy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sqlalchemy) (4.14.1)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ikawahyuni/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/ikawahyuni/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [27]:
from sqlalchemy import create_engine, text
import pandas as pd

# Gunakan kredensial yang SAMA dengan di DBeaver
server = 'localhost'
port = '5433'  # port yang sama dengan DBeaver
database = 'postgres'
username = 'postgres'
password = 'ikawahyuni1234'

# Connection string PostgreSQL
connection_string = f"postgresql://{username}:{password}@{server}:{port}/{database}"

engine = create_engine(connection_string)

# Tes koneksi
try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT version()")).fetchone()
        print("✅ Koneksi berhasil!")
        print(result[0])
except Exception as e:
    print("❌ Koneksi gagal:")
    print(e)

✅ Koneksi berhasil!
PostgreSQL 18.1 (Postgres.app) on aarch64-apple-darwin23.6.0, compiled by Apple clang version 15.0.0 (clang-1500.3.9.4), 64-bit

In [28]:
try:
    df.to_sql(
        name='netflix',           # nama tabel di PostgreSQL
        con=engine,              # koneksi engine
        if_exists='replace',     # 'replace', 'append', atau 'fail'
        index=False              # tidak menyimpan index sebagai kolom
    )
    print("✅ Data berhasil ditransfer ke PostgreSQL!")
    print(f"Jumlah baris: {len(df)}")
except Exception as e:
    print("❌ Transfer gagal:")
    print(e)

✅ Data berhasil ditransfer ke PostgreSQL!
Jumlah baris: 8807

In [29]:
df[df.show_id=='s5972']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5971,s5972,Movie,(T)ERROR,"Lyric R. Cabral, David Felix Sutcliffe",NaN,United States,"June 30, 2016",2015,NR,84 min,Documentaries,This real-life look at FBI counterterrorism op...

In [ ]:
#dibutuhkan jika di sql format column varchar (----) 
max(df.type.str.len())
--max(df.title.str.len())
--max(df.director.str.len())
--max(df.country.str.len())
--max(df.date_added.str.len())
--max(df.rating.str.len())

7

In [32]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64